name: riverpod_state
description: The missing idle state to async provider, support code generation
version: 0.1.0
homepage: https://github.com/masreplay/riverpod_state

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.5

  custom_lint:
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
