name: riverpod_state
description: Add idle state to async provider, support code generation
version: 0.0.1
homepage: https://github.com/masreplay/riverpod_state

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  custom_lint:
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter: